- lineinfile:
    path: "{{ home_dir }}/.bash_aliases"
    backup: yes
    create: yes
    line: "alias {{ item }}"
  with_items:
    - ll='ls -alF'

- copy:
    src: files/backup.bash
    dest: "{{ home_dir }}/backup"
    mode: 0764
