- become: yes
  apt:
    pkg: default-jre
    state: present
    force: yes

- file:
    path: "{{ home_dir }}/.apps/VioletUmlEditor"
    state: directory

- unarchive:
    src: https://github.com/petrknap/violetumleditor/archive/v2.1.0.zip
    dest: "{{ home_dir }}/.apps/VioletUmlEditor"
    creates: "{{ home_dir }}/.apps/VioletUmlEditor/violetumleditor-2.1.0"
    remote_src: yes

- template:
    src: templates/VioletUmlEditor.desktop
    dest: "{{ home_dir }}/Desktop/VioletUmlEditor.desktop"
    mode: 0774
